[package]
name = "rust_api_internship"
version = "0.1.0"
authors = ["Killy85 <goureau.n.a@hotmail.fr>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = "0.15"
rocket = "*"
rocket_codegen = "*"