[package]
name = "rust_api_internship"
version = "0.1.0"
authors = ["Killy85 <goureau.n.a@hotmail.fr>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
postgres = "*"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
